"""
Eco-Bridge -- Report Generation Agent
"""

import os
from datetime import datetime
from scoring_agent import score_sme


def generate_report_markdown(sme_id: str) -> str:
    result = score_sme(sme_id)
    fp = result["footprint"]
    rubric = result["rubric"]
    explanation = result["explanation"]

    score = rubric.get("score")
    if score is None:
        return f"# Compliance Report -- {sme_id}\n\nInsufficient data to generate a report."

    if score >= 80:
        rating = "Strong"
    elif score >= 50:
        rating = "Moderate"
    else:
        rating = "Needs Improvement"

    report = f"""# Eco-Bridge Sustainability Compliance Report

**SME ID:** {sme_id}
**Supplier:** {fp.get('supplier_name', 'N/A')}
**Location:** {fp['location']}
**Material:** {fp['material']}
**Report generated:** {datetime.now().strftime('%d %B %Y')}

---

## Compliance Score: {score}/100  ({rating})

| Metric | Value |
|---|---|
| Monthly production | {fp['monthly_production_kg']} kg |
| Scope 2 emissions (grid electricity) | {fp['scope2_ghg_kgco2e']} kgCO2e |
| Scope 1/3 emissions (manufacturing process) | {fp['scope1_3_ghg_kgco2e']} kgCO2e |
| Total emissions | {fp['total_ghg_kgco2e']} kgCO2e |
| Emissions intensity | {rubric['actual_ghg_per_kg']} kgCO2e/kg |
| Best-case benchmark (cleanest process + grid, sourced) | {rubric['best_case_ghg_per_kg']} kgCO2e/kg |
| Worst-case benchmark (least efficient process + grid, sourced) | {rubric['worst_case_ghg_per_kg']} kgCO2e/kg |

---

## Analysis & Recommendations

{explanation}

---

## Data Sources & Methodology

- Scope 2 grid factor: Google's Regional Carbon-Free Energy dataset (BigQuery public dataset)
- Scope 1/3 process factors: Carbonfact Open Source LCA Database (CC-BY-SA 4.0)
- Scoring method: Position between the best and worst real emission profiles found in the sourced dataset
- Note: Grid carbon intensity for {fp['location']} was {"sourced directly from regional data" if fp.get('grid_intensity_used_g_per_kwh') != 640 else "estimated using an India-average fallback, as this specific location is not yet in our grid dataset"}

*This report was generated by Eco-Bridge, an agentic sustainability auditor built for Patchamomma 2026.*
"""
    return report


def save_report(sme_id: str, output_dir: str = ".") -> str:
    report_text = generate_report_markdown(sme_id)
    filepath = os.path.join(output_dir, f"compliance_report_{sme_id}.md")
    with open(filepath, "w") as f:
        f.write(report_text)
    return filepath


if __name__ == "__main__":
    path = save_report("SME0071")
    print(f"Report saved to: {path}")
    print()
    print(generate_report_markdown("SME0071"))
